### ISSUE TITLE
Should use enums instead of lists

### ISSUE THREAD

**Issue by Snickdx** [uwidcit/nature-seekers-backend#1]
https://github.com/uwidcit/nature-seekers-backend/blob/2a105347b75a28e0aadc07227e0f791c5c4bcb7d/App/models/turtletag.py#L13

Your list types should be enums, example:

https://github.com/uwidcit/pharm-backend/blob/577c7b4086ba36f39223a7917caebf4acf74eedb/App/models/productOrder.py#L5

**Comment by kenny98** [comment]
Enum types used instead of mutable objects - issue will be closed.
