### ISSUE TITLE
All timestamps should default to utc now

### ISSUE THREAD

**Issue by Snickdx** [uwidcit/nature-seekers-backend#4]
https://github.com/uwidcit/nature-seekers-backend/blob/4e84c735574764f7c75e6a9a6bcdcd5f4da5ad09/App/models/excavation.py#L6

Timestamps should default to server time example: https://github.com/uwidcit/game-rental-backend/blob/main/App/models/listing.py

**Comment by kenny98** [comment]
Updates made on this pull request
https://github.com/uwidcit/nature-seekers-backend/pull/5
